name: Publish

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: MineInAbyss/publish-action@develop
        with:
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
          release-files: |
            ${{ github.workspace }}/publish/*.jar
